// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarspearOnlineApi.Data;

#nullable disable

namespace WarspearOnlineApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241111212407_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.DropJournalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DropJournalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DropDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("Drop_Date");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("rf_GroupID");

                    b.Property<int>("ObjectId")
                        .HasColumnType("int")
                        .HasColumnName("rf_ObjectID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.ToTable("DropJournal", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.DropJournalPlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DropJournalPlayerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DropJournalId")
                        .HasColumnType("int")
                        .HasColumnName("rf_DropJournalID");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("rf_PlayerID");

                    b.HasKey("Id");

                    b.ToTable("DropJournalPlayer", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.FractionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FractionName");

                    b.HasKey("Id");

                    b.ToTable("Fraction", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.GroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GroupID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.GroupGuildEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GroupGuildID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("rf_GroupID");

                    b.Property<int>("GuildId")
                        .HasColumnType("int")
                        .HasColumnName("rf_GuildID");

                    b.HasKey("Id");

                    b.ToTable("GroupGuild", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.GuildEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GuildID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FractionId")
                        .HasColumnType("int")
                        .HasColumnName("rf_FractionID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<int>("ServerId")
                        .HasColumnType("int")
                        .HasColumnName("rf_ServerID");

                    b.HasKey("Id");

                    b.ToTable("Guild", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.ObjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ObjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ObjectName");

                    b.Property<int>("ObjectTypeId")
                        .HasColumnType("int")
                        .HasColumnName("rf_ObjectTypeID");

                    b.HasKey("Id");

                    b.ToTable("Object", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.ObjectTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ObjectTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ObjectTypeName");

                    b.HasKey("Id");

                    b.ToTable("ObjectType", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlayerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FractionId")
                        .HasColumnType("int")
                        .HasColumnName("rf_FractionID");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nick");

                    b.Property<int>("ServerId")
                        .HasColumnType("int")
                        .HasColumnName("rf_ServerID");

                    b.HasKey("Id");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.ServerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ServerName");

                    b.HasKey("Id");

                    b.ToTable("Server", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
