// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarspearOnlineApi.Data;

#nullable disable

namespace WarspearOnlineApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241112232525_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.wo_Drop", b =>
                {
                    b.Property<int>("DropID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DropID"));

                    b.Property<DateTime>("Drop_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("rf_GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rf_GroupID");

                    b.Property<int>("rf_ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rf_ObjectID");

                    b.HasKey("DropID");

                    b.HasIndex("rf_GroupID");

                    b.HasIndex("rf_ObjectID");

                    b.ToTable("wo_Drop", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.wo_DropPlayer", b =>
                {
                    b.Property<int>("DropPlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DropPlayerID"));

                    b.Property<int>("rf_DropID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rf_DropID");

                    b.Property<int>("rf_PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rf_PlayerID");

                    b.HasKey("DropPlayerID");

                    b.ToTable("wo_DropPlayer", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.wo_Fraction", b =>
                {
                    b.Property<int>("DropPlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DropPlayerID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DropPlayerID");

                    b.ToTable("wo_Fraction", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.wo_Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupID");

                    b.ToTable("wo_Group", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.wo_GroupGuild", b =>
                {
                    b.Property<int>("GroupGuildID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupGuildID"));

                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rf_GroupID");

                    b.Property<int>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rf_GuildID");

                    b.HasKey("GroupGuildID");

                    b.ToTable("wo_GroupGuild", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.wo_Guild", b =>
                {
                    b.Property<int>("GuildID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuildID"));

                    b.Property<int>("FractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rf_FractionID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rf_ServerID");

                    b.HasKey("GuildID");

                    b.ToTable("wo_Guild", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.wo_Object", b =>
                {
                    b.Property<int>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjectID"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObjectTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rf_ObjectTypeID");

                    b.HasKey("ObjectID");

                    b.ToTable("wo_Object", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.wo_ObjectType", b =>
                {
                    b.Property<int>("ObjectTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjectTypeID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObjectTypeID");

                    b.ToTable("wo_ObjectType", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.wo_Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerID"));

                    b.Property<int>("FractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rf_FractionID");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("rf_ServerID");

                    b.HasKey("PlayerID");

                    b.ToTable("wo_Player", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.wo_Server", b =>
                {
                    b.Property<int>("ServerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServerID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServerID");

                    b.ToTable("wo_Server", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.wo_Drop", b =>
                {
                    b.HasOne("WarspearOnlineApi.Models.Entity.wo_Group", "Group")
                        .WithMany("Drops")
                        .HasForeignKey("rf_GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarspearOnlineApi.Models.Entity.wo_Object", "Object")
                        .WithMany("Drops")
                        .HasForeignKey("rf_ObjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.wo_Group", b =>
                {
                    b.Navigation("Drops");
                });

            modelBuilder.Entity("WarspearOnlineApi.Models.Entity.wo_Object", b =>
                {
                    b.Navigation("Drops");
                });
#pragma warning restore 612, 618
        }
    }
}
