// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarspearOnlineApi.Api.Data;

#nullable disable

namespace WarspearOnlineApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250112153725_InitMigration4")]
    partial class InitMigration4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Intersections.wo_DropPlayer", b =>
                {
                    b.Property<int>("DropPlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DropPlayerID"));

                    b.Property<bool>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Part")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("rf_DropID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("rf_PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("DropPlayerID");

                    b.HasIndex("rf_DropID");

                    b.HasIndex("rf_PlayerID");

                    b.ToTable("wo_DropPlayer", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Intersections.wo_GroupGuild", b =>
                {
                    b.Property<int>("GroupGuildID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupGuildID"));

                    b.Property<int>("rf_GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("rf_GuildID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("GroupGuildID");

                    b.HasIndex("rf_GroupID");

                    b.HasIndex("rf_GuildID");

                    b.ToTable("wo_GroupGuild", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Intersections.wo_UserGroup", b =>
                {
                    b.Property<int>("UserGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserGroupID"));

                    b.Property<int>("rf_GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("rf_UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("UserGroupID");

                    b.HasIndex("rf_GroupID");

                    b.HasIndex("rf_UserID");

                    b.ToTable("wo_UserGroup", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Users.wo_AccessLevel", b =>
                {
                    b.Property<int>("AccessLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessLevelID"));

                    b.Property<string>("AccessLevelCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<int>("AccessLevelInt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("AccessLevelName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<int>("rf_ParentAccessLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("AccessLevelID");

                    b.HasIndex("rf_ParentAccessLevelID");

                    b.ToTable("wo_AccessLevel", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Users.wo_AccessLevelRole", b =>
                {
                    b.Property<int>("AccessLevelRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessLevelRoleID"));

                    b.Property<int>("rf_AccessLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("rf_RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("AccessLevelRoleID");

                    b.HasIndex("rf_AccessLevelID");

                    b.HasIndex("rf_RoleID");

                    b.ToTable("wo_AccessLevelRole", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Users.wo_Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.HasKey("RoleID");

                    b.ToTable("wo_Role", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Users.wo_User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.Property<int>("RangeAccessLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<int>("rf_AccessLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("rf_FractionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("rf_ServerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("UserId");

                    b.HasIndex("rf_AccessLevelID");

                    b.HasIndex("rf_FractionID");

                    b.HasIndex("rf_ServerID");

                    b.ToTable("wo_User", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Class", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<int>("rf_FractionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ClassID");

                    b.HasIndex("rf_FractionID");

                    b.ToTable("wo_Class", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Drop", b =>
                {
                    b.Property<int>("DropID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DropID"));

                    b.Property<DateTime>("Drop_Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<int>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("rf_GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("rf_ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("DropID");

                    b.HasIndex("rf_GroupID");

                    b.HasIndex("rf_ObjectID");

                    b.ToTable("wo_Drop", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_DropStatus", b =>
                {
                    b.Property<int>("DropStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DropStatusID"));

                    b.Property<string>("DropStatusCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.Property<string>("DropStatusName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.HasKey("DropStatusID");

                    b.ToTable("wo_DropStatus", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Fraction", b =>
                {
                    b.Property<int>("FractionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FractionID"));

                    b.Property<string>("FractionCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("FractionName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.HasKey("FractionID");

                    b.ToTable("wo_Fraction", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupID"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.Property<int>("rf_FractionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("rf_ServerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("rf_UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("GroupID");

                    b.HasIndex("rf_FractionID");

                    b.HasIndex("rf_ServerID");

                    b.ToTable("wo_Group", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Guild", b =>
                {
                    b.Property<int>("GuildID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuildID"));

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.Property<int>("rf_FractionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("rf_ServerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("rf_UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("GuildID");

                    b.HasIndex("rf_FractionID");

                    b.HasIndex("rf_ServerID");

                    b.ToTable("wo_Guild", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Object", b =>
                {
                    b.Property<int>("ObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjectID"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4096)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("ObjectCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValue("");

                    b.Property<int>("rf_ObjectTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ObjectID");

                    b.HasIndex("rf_ObjectTypeID");

                    b.ToTable("wo_Object", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_ObjectType", b =>
                {
                    b.Property<int>("ObjectTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjectTypeID"));

                    b.Property<string>("ObjectTypeCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.Property<string>("ObjectTypeName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.HasKey("ObjectTypeID");

                    b.ToTable("wo_ObjectType", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerID"));

                    b.Property<string>("Nick")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<int>("rf_ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("rf_FractionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("rf_ServerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("PlayerID");

                    b.HasIndex("Nick");

                    b.HasIndex("rf_ClassID");

                    b.HasIndex("rf_FractionID");

                    b.HasIndex("rf_ServerID");

                    b.ToTable("wo_Player", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Server", b =>
                {
                    b.Property<int>("ServerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServerID"));

                    b.Property<string>("ServerCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.HasKey("ServerID");

                    b.ToTable("wo_Server", (string)null);
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Intersections.wo_DropPlayer", b =>
                {
                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Drop", "rf_Drop")
                        .WithMany("DropPlayers")
                        .HasForeignKey("rf_DropID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Player", "rf_Player")
                        .WithMany("DropPlayers")
                        .HasForeignKey("rf_PlayerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("rf_Drop");

                    b.Navigation("rf_Player");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Intersections.wo_GroupGuild", b =>
                {
                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Group", "rf_Group")
                        .WithMany("GroupGuilds")
                        .HasForeignKey("rf_GroupID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Guild", "rf_Guild")
                        .WithMany("GroupGuilds")
                        .HasForeignKey("rf_GuildID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("rf_Group");

                    b.Navigation("rf_Guild");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Intersections.wo_UserGroup", b =>
                {
                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Group", "rf_Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("rf_GroupID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.Users.wo_User", "rf_User")
                        .WithMany("UserGroups")
                        .HasForeignKey("rf_UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("rf_Group");

                    b.Navigation("rf_User");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Users.wo_AccessLevel", b =>
                {
                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.Users.wo_AccessLevel", "rf_ParentAccessLevel")
                        .WithMany("ChildAccessLevels")
                        .HasForeignKey("rf_ParentAccessLevelID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("rf_ParentAccessLevel");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Users.wo_AccessLevelRole", b =>
                {
                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.Users.wo_AccessLevel", "rf_AccessLevel")
                        .WithMany("AccessLevelRoles")
                        .HasForeignKey("rf_AccessLevelID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.Users.wo_Role", "rf_Role")
                        .WithMany("AccessLevelRoles")
                        .HasForeignKey("rf_RoleID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("rf_AccessLevel");

                    b.Navigation("rf_Role");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Users.wo_User", b =>
                {
                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.Users.wo_AccessLevel", "rf_AccessLevel")
                        .WithMany("Users")
                        .HasForeignKey("rf_AccessLevelID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Fraction", "rf_Fraction")
                        .WithMany("Users")
                        .HasForeignKey("rf_FractionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Server", "rf_Server")
                        .WithMany("Users")
                        .HasForeignKey("rf_ServerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("rf_AccessLevel");

                    b.Navigation("rf_Fraction");

                    b.Navigation("rf_Server");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Class", b =>
                {
                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Fraction", "rf_Fraction")
                        .WithMany("Classes")
                        .HasForeignKey("rf_FractionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("rf_Fraction");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Drop", b =>
                {
                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Group", "rf_Group")
                        .WithMany("Drops")
                        .HasForeignKey("rf_GroupID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Object", "rf_Object")
                        .WithMany("Drops")
                        .HasForeignKey("rf_ObjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("rf_Group");

                    b.Navigation("rf_Object");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Group", b =>
                {
                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Fraction", "rf_Fraction")
                        .WithMany("Groups")
                        .HasForeignKey("rf_FractionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Server", "rf_Server")
                        .WithMany("Groups")
                        .HasForeignKey("rf_ServerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("rf_Fraction");

                    b.Navigation("rf_Server");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Guild", b =>
                {
                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Fraction", "rf_Fraction")
                        .WithMany("Guilds")
                        .HasForeignKey("rf_FractionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Server", "rf_Server")
                        .WithMany("Guilds")
                        .HasForeignKey("rf_ServerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("rf_Fraction");

                    b.Navigation("rf_Server");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Object", b =>
                {
                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_ObjectType", "rf_ObjectType")
                        .WithMany("Objects")
                        .HasForeignKey("rf_ObjectTypeID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("rf_ObjectType");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Player", b =>
                {
                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Class", "rf_Class")
                        .WithMany("Players")
                        .HasForeignKey("rf_ClassID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Fraction", "rf_Fraction")
                        .WithMany("Players")
                        .HasForeignKey("rf_FractionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarspearOnlineApi.Api.Models.Entity.wo_Server", "rf_Server")
                        .WithMany("Players")
                        .HasForeignKey("rf_ServerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("rf_Class");

                    b.Navigation("rf_Fraction");

                    b.Navigation("rf_Server");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Users.wo_AccessLevel", b =>
                {
                    b.Navigation("AccessLevelRoles");

                    b.Navigation("ChildAccessLevels");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Users.wo_Role", b =>
                {
                    b.Navigation("AccessLevelRoles");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.Users.wo_User", b =>
                {
                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Class", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Drop", b =>
                {
                    b.Navigation("DropPlayers");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Fraction", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Groups");

                    b.Navigation("Guilds");

                    b.Navigation("Players");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Group", b =>
                {
                    b.Navigation("Drops");

                    b.Navigation("GroupGuilds");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Guild", b =>
                {
                    b.Navigation("GroupGuilds");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Object", b =>
                {
                    b.Navigation("Drops");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_ObjectType", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Player", b =>
                {
                    b.Navigation("DropPlayers");
                });

            modelBuilder.Entity("WarspearOnlineApi.Api.Models.Entity.wo_Server", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Guilds");

                    b.Navigation("Players");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
